# Actividad - Trabajando con DataFrames de Pandas.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: pandas_df_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter
* Deben trabajar con el datasets adjunto a la actividad

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

In [ ]:
import pandas as pd
import sqlite3

#Aqui agrega la conexión a la base de datos

conn = sqlite3.connect('Salaries.sqlite')

#Crea el dataframe con los datos del datasets

df = pd.read_sql_query('SELECT * FROM Salaries', conn)

conn.close()

In [3]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,None,567595.43,567595.43,2011,None,San Francisco,None
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,None,538909.28,538909.28,2011,None,San Francisco,None
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,None,335279.91,335279.91,2011,None,San Francisco,None
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,None,332343.61,332343.61,2011,None,San Francisco,None
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,None,326373.19,326373.19,2011,None,San Francisco,None

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       object
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(2), int64(2), object(9)
memory usage: 14.7+ MB

1. **Top 10 empleados con mayor salario total (incluyendo beneficios)**
Extrae e imprime un top 10 de expleados con mayor salario incluyendo los beneficios

In [ ]:
#todo
# ordenamos en base a la columna 'TotalPayBenefits' de forma descendente y tomamos los primeros 10 registros
top_10_empleados = df.sort_values(by='TotalPayBenefits', ascending=False).head(10)

print(top_10_empleados[['EmployeeName','TotalPayBenefits']])

                EmployeeName  TotalPayBenefits
0             NATHANIEL FORD         567595.43
1               GARY JIMENEZ         538909.28
110531           David Shinn         510732.68
110532            Amy P Hart         479652.21
110533  William J Coaker Jr.         436224.36
72925         Gregory P Suhr         425815.28
72926   Joanne M Hayes-White         422353.40
110534        Gregory P Suhr         418019.22
110535  Joanne M Hayes-White         417435.10
110536       Ellen G Moffatt         415767.94

2. **Filtrar empleados con más de 50,000 en horas extra, la columna a tratar es: (OvertimePay)**

In [ ]:
# para aplicar un filtro necesitamos convertir la columna 'OvertimePay' a un tipo numérico
# de lo contrario obtenemos un ValueError.
df['OvertimePay'] = pd.to_numeric(df['OvertimePay'], errors='coerce')

In [ ]:
#todo
empleados_horas_extra = df[df['OvertimePay'] > 50000]

# mostramos los primeros 10 registros luego de aplicar el filtro
print(empleados_horas_extra[['EmployeeName','OvertimePay']].head(10))
print(f'\nempleados con más de 50k en horas extra: {len(empleados_horas_extra)}')

         EmployeeName  OvertimePay
1        GARY JIMENEZ    245131.88
2      ALBERT PARDINI    106088.18
3   CHRISTOPHER CHONG     56120.71
6           ALSON LEE     89062.90
8      MICHAEL MORRIS     86362.68
10      ARTHUR KENNEY     71344.88
11   PATRICIA JACKSON     87082.62
14     DAVID FRANKLIN     74050.30
15    RICHARD CORRIEA     73478.20
17     SEBASTIAN WONG    119397.26

empleados con más de 50k en horas extra: 2165

3. **Contar cuántos empleados únicos hay por año**

In [44]:
#todo
empleados_por_año = df.groupby('Year')['EmployeeName'].nunique()
print(f'cantidad de empleados por año: \n{empleados_por_año}')

cantidad de empleados por año:
Year
2011    33878
2012    34349
2013    36150
2014    36684
Name: EmployeeName, dtype: int64

4. **Ver cuántos cargos únicos (JobTitle) existen y los 5 más comunes**

In [ ]:
cargos_unicos = df['JobTitle'].nunique()
print(f'existen: {cargos_unicos} cargos únicos')

existen: 2159 cargos únicos

In [ ]:
#todo
# con size() contamos la cantidad de registros por cada grupo
# y sort_values para ordenarlos de forma descendente,
# para conseguir los 5 cargos más comunes
cantidad_cargos_unicos = df.groupby('JobTitle').size().sort_values(ascending=False).head(5)

print(f'cargos más comunes: \n{cantidad_cargos_unicos}')

cargos más comunes:
JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
dtype: int64

5. **Mostrar el salario total (TotalPay) promedio por año**

In [ ]:
#todo
# agrupamos por año y la columna 'TotalPay', luego aplicamos la función mean() para el promedio,
# y round(2) para redondear a 2 decimales
salario_tota_promedio_por_año = df.groupby('Year')['TotalPay'].mean().round(2)

print(salario_tota_promedio_por_año)

Year
2011    71744.10
2012    74113.26
2013    77611.44
2014    75463.92
Name: TotalPay, dtype: float64

6. **Exporta todos los datos a un CSV y muestra los ultimos 10 valores**

In [ ]:
#todo
# para exportar el dataframe a un archivo CSV, usamos el método to_csv()
# index en false para no incluir el índice en el CSV
df.to_csv('Salaries.csv', index=False)

# y mostramos los ultimos 10 registros
df.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.00,0.0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148646,148647,Not provided,Not provided,Not Provided,NaN,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0.0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0.0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,NaN,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148651,148652,Not provided,Not provided,Not Provided,NaN,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148652,148653,Not provided,Not provided,Not Provided,NaN,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.0,-618.13,0.00,-618.13,-618.13,2014,None,San Francisco,PT